---
- name: ANSIBLE - Shop Installation
  hosts: kloud
  #  sudo: yes
  become: yes
  become_method: sudo
  vars_prompt:
    - name: "githubuser"
      prompt: "Enter your github username"
      private: no
    - name: "githubpassword"
      prompt: "Enter your github password"
      private: yes

  tasks:
      - name: pull down changes from server
        command: git pull origin prod1.1 chdir=/usr/share/nginx/html/kloudhive


#  tasks:
#    - name: Get Clone of the Repository
#      git: repo=http://{{ githubuser }}:{{ githubpassword }}@gitlab.kelltontech.net/kloudhive/kloudhive.git  dest=/usr/share/nginx/html/kloudhive version=prod1.1
